### PR TITLE
Show tag information and license as image badges

### PR DESCRIPTION
**Pull request by tstibor**

### CODE REVIEW

**Comment by dstndstn** [comment]
The only problem is that the license is a little more complicated... technically the whole thing has to ship as GPLv2 because of some dependencies.

**Comment by tstibor** [comment]
How about modifying it to either:

1.) Removing  the bsd3 image badge and just leave the tag image badge
or
2.) Replacing the bsd3 image badge by the gpl2 image badge
or
3.) Adding an additional gpl2 image badge to the bsd3 and tag image badges

Cheers
 Thomas

**Comment by dstndstn** [comment]
I believe (2) is the right way to go.  Thanks!

**Comment by dstndstn** [comment]
Thank you!

**Pull request merged**
