### PR TITLE
Improved version of Client.py

### PR DESCRIPTION
**Pull request by GeorgViehoever**
Hi Dustin,
as requested, here is the pull request for the Extended Version of Client.py.
Thanks,
Georg

### CODE REVIEW

**Comment by dstndstn** [comment]
Normally, one uses "#!/usr/bin/env" rather than "#!/bin/env"; see
http://en.wikipedia.org/wiki/Shebang_%28Unix%29

Other than that, looks great!  Thank you!

**Comment by GeorgViehoever** [comment]
Hi Dustin,

thanks for pointing out the /usr/bin/env issue. /bin/env works fine on Fedora, but apparently not on some other Linuxes.
I have no idea what to do about the AppVeyor failed message. Feel free to make the necessary changes.

Georg

**Comment by jbglaw** [comment]
On Mon, 2015-02-23 10:19:17 -0800, Georg Viehoever <notifications@github.com> wrote:
> Hi Dustin,
> 
> thanks for pointing out the /usr/bin/env issue. /bin/env works fine
> on Fedora, but apparently not on some other Linuxes.
>
> I have no idea what to do about the AppVeyor failed message. Feel
> free to make the necessary changes.

I would have expected `env' to sit in /usr/bin, but don't ask why. I
use it almost exclusively for all my scripts, so the caller can, by
setting $PATH, choose which `bash', `sh', `python' et al. to choose.

  However, I always use #!/usr/bin/env, never ever used #!/bin/env.

MfG, JBG

-- 
      Jan-Benedict Glaw      jbglaw@lug-owl.de              +49-172-7608481
Signature of:              Fortschritt bedeutet, einen Schritt so zu machen,
the second  :                   daß man den nächsten auch noch machen kann.

**Comment by dstndstn** [comment]
The AppVeyor build isn't set up yet (doesn't build in master), so false alarm.

Thanks for the /usr/bin/env change, and for contributing this code!

**Pull request merged**
