### PR TITLE
Bring nova into the Python 3 world

### PR DESCRIPTION
**Pull request by bnavigator**
I have to migrate our local nova server and want to get rid of Python 2. From #148 I gathered that the solver should be ready for Python 3, but in my attempt the `net` part kept failing.

I think I have fixed most of the obvious code lines specific to python 2 such as the transition of `urllib` and some `str` vs `byte` TypeErrors when dealing with file i/o streams.

I have not attained full functionality of my local nova installation yet, but at least I do not get any exceptions thrown at my by the webserver anymore. Don't know yet if the remaining issues have to do with Python 3 or other parts of the setup.

### CODE REVIEW

**Comment by bnavigator** [comment]
I don't think the Travis CI fail has anything to do with the PR

**Comment by dstndstn** [comment]
This is great -- you're right, the travis failure is due to an error building the dependency 'fitsio', which then trickles down to make tests fail.  I should pin fitsio to a specific version...

Let me know if/when you get stuck and I can take a look.

For what it's worth, on the nova site we're running django 1.11.2 (I should upgrade to 1.11.28).

**Comment by bnavigator** [comment]
I think I made some good progress. I'll let our users test further on the local nova, but my rudimentary tests of submitting and viewing files seems to work. Please have a look.

**Comment by bnavigator** [comment]
Update: Our users report that the local nova installation running on FreeBSD with Python 3.7 works as expected.

**Comment by dstndstn** [comment]
Thanks for this!  Will try to take a look, test and merge today.

**Comment by dstndstn** [comment]
hey, sorry for my delay on this.  Just testing it in our supernova.astrometry.net testbed.  All looks good so far...

**Comment by dstndstn** [comment]
Now live at nova.astrometry.net -- thank you again for this!!

**Pull request merged**
