### PR TITLE
Add manpages to the astrometry.net executables.

### PR DESCRIPTION
**Pull request by olebole**
Manpages are required by the Debian distribution, and hereby contributed upstream.
The manpages were generated by help2man and then significantly polished manually.
Some executables are still undocumented: `coadd`, `plotstuff`, `search-index`, and `wcs-to-tan`.

### CODE REVIEW

**Comment by dstndstn** [comment]
coadd, plotstuff, and search-index can be eliminated.

This is awesome -- thank you very much!

**Comment by dstndstn** [comment]
Also, please [feel free to] add yourself to the list of contributors in the README.md

**Comment by olebole** [comment]
Hi Dustin, I am confused that you appreciated the pull request but then closed it? Shall I open a new one with your changes (rm coadd.1 plotstuff.1 search-index.1; add myself to Readme.md)?

**Comment by dstndstn** [comment]
Oh, sorry, too quick on the Merge button!  I'll just delete those man pages (and not install those binaries), and add you to the README.  Thanks again for this -- it's great!

**Comment by dstndstn** [comment]
Apologies, I thought I had already merged this!  Thank you.
(PS, in 05e2baa I'm installing the man pages in share/man/man1 -- hope that's the right place for them!)

**Pull request merged**
