### PR TITLE
Python modernization

### PR DESCRIPTION
**Pull request by timj**
First modernization pass. I haven't actually tested it yet (I'm using python 3) but the fixes are pretty standard:

* Replace all the tabs with 4 spaces. This will be needed by Python 3 and hopefully has not messed up Python 2. It was messing up the modernization tool.
* Use print_function and absolute_import from `__future__`.
* Do not throw string exceptions, use RuntimeError instead
* "as e" vs ", e" exception catching.

### CODE REVIEW

**Comment by timj** [comment]
This PR is a pre-requisite to #87

**Comment by parejkoj** [comment]
This is about to become a blocker on further LSST conversion to python 3: meas_astrom depends on astrometry.net and most of the remaining packages depend on meas_astrom.

**Comment by dstndstn** [comment]
Sorry for my slowness.  Thanks for this!

**Comment by timj** [comment]
I did notice that some of the code layout is a bit strange mixing scripts with modules. It would be cleaner if the scripts were one place and the importable code was in a proper package with an `__init__.py`.

**Comment by parejkoj** [comment]
Executable code should live in `bin/`, not in the module directory. If the executable code contains library-like things that are needed elsewhere, those should live in the module directory and the executable can be short (import, main, argparse).

**Comment by dstndstn** [comment]
Note that the scripts in bin/ are symlinks into the modules directory.

What is your recommended way of picking up the correct PYTHONPATH from a script?

Say, in bin/image2pnm.py, how do I make sure that ../lib/python is in my pythonpath?

**Comment by timj** [comment]
I'd add `os.path.join(os.path.dirname(__file__), os.path.pardir, "lib")` to `sys.path` in the script.

**Comment by parejkoj** [comment]
If astrometry.net were pip-installable, one could use conda environments or other virtualenv tools to manage the pythonpath. Doing it at the top of the script is asking for trouble (particularly if a.net is installed in e.g. `/usr/local/`, with the executables going in `bin/` and the python going somewhere deep in a site-packages directory).

**Comment by timj** [comment]
I thought we were trying to solve a problem when things aren't installed using pip. Adding ../lib to sys.path (especially at the end) won't hurt anything.

**Pull request merged**
