### PR TITLE
Wrong trueorder in resort test.

### PR DESCRIPTION
**Pull request by tstibor**
Running test in blind folder results in:
blind>./test
There was 1 failure:
1) test_sorting: test_resort-xylist.c:72: expected <763.000000> but was <690.000000>

!!!FAILURES!!!
Runs: 7 Passes: 6 Fails: 1

Changing the trueorder to:
-       int trueorder[] = { 4, 5, 7, 6, 2, 0, 1, 3 };
-       int trueorder[] = { 4, 5, 6, 7, 0, 2, 1, 3 };

Let the test pass.
.......
OK (7 tests)

### CODE REVIEW

**Comment by dstndstn** [comment]
Why do you think that is the right order?  Maybe the test is failing for a good reason.  Before we change the "truth" I'd like to see a little more analysis.

**Comment by tstibor** [comment]
According to the code:
```CuAssertIntEquals(tc, 0, resort_xylist(infn, outfn, NULL, NULL, TRUE)```

It is sorted according to the flux values in

```
int resort_xylist(const char* infn, const char* outfn,
                  const char* fluxcol, const char* backcol,
                  int ascending) {

// Sort by flux...
perm1 = permuted_sort(flux, sizeof(double), compare, NULL, N);
...
}
```
The flux values in the double array are
```
void test_sorting(CuTest* tc) {
        double flux[] = { 50, 100, 50, 100, 20, 20, 40, 40 };
        ...
}
```
Writing them with an index gives
```
0:50, 1:100, 2:50, 3:100, 4:20, 5:20, 6:40, 7:40
```
Sorting them gives index array
```
20, 20, 40, 40, 50, 50, 100
index: 4, 5, 6, 7, 0, 2, 1, 3
```
which is the correct true order
```
int trueorder[] = { 4, 5, 6, 7, 0, 2, 1, 3 };
```

**Comment by dstndstn** [comment]
No, resort_xylist does something more complicated.  It sorts by
background-subtracted and non-background-subtracted fluxes, and interleaves
those two lists without repeats (line 151).

**Comment by tstibor** [comment]
Ahh OK, I misunderstood the function. Is the test passing on your machine?

**Comment by dstndstn** [comment]
Yes.

My guess is that the "true" test result depends on a stable sorting
algorithm, or matches the specific results from some algorithm (eg,
quicksort).  So you're probably right that the test is wrong :)

**Comment by dstndstn** [comment]
the flux+bg sorted order is 5,4,7,6,0,2,3,1

in your ordering above, 4,5 could swap, as could 6,7 and 0,2 and 1,3.

I would say tweak the test by making the values unique (40 and 41, eg).

Thanks for looking into this!

I added a little documentation in the header file.

**Pull request closed without merging**
